### ISSUE TITLE
Api Docs on Github or main site don't include `include_runfiles` attribute of `pkg_tar`

### ISSUE THREAD

**Issue by samhowes** [bazelbuild/rules_pkg#356] opened 2021-05-20 16:48 UTC
`pkg_tar` has the attribute `include_runfiles`: https://github.com/bazelbuild/rules_pkg/blob/e24fbddf6de7378ed0ffab78befc1cc1cc57791b/pkg/pkg.bzl#L368

Which is not listed in the attributes at: https://github.com/bazelbuild/rules_pkg/blob/main/pkg/docs/reference.md#pkg_tar
Or in the attributes at: https://docs.bazel.build/versions/master/be/pkg.html#pkg_tar

But is listed at: https://docs.aspect.dev/bazelbuild/rules_pkg/0.4.0/pkg/pkg_tar.html#pkg_tar_impl-include_runfiles

**Comment by aiuto** [comment] 2021-05-20 18:01
Duplicate of #145, but see #153 for the solutions we are going to be using in place of include_runfiles.

**Closed by aiuto** 2021-05-20 18:01 UTC
