### ISSUE TITLE
rules_pkg builds debs with incompatible PAX format

### ISSUE THREAD

**Issue by itdaniher** [bazelbuild/rules_pkg#203] opened 2020-07-13 22:52 UTC
Python 3.8 changed the [default format](https://docs.python.org/3/library/tarfile.html#tarfile.DEFAULT_FORMAT) of tarfiles from `GNU_FORMAT` to `PAX_FORMAT`.

`TAR_FILETYPE_PAX_EXTENDED` tarfiles are rejected by DPKG with the messages "corrupted filesystem tarfile in package archive:" and ["unsupported PAX tar header type"](https://git.launchpad.net/ubuntu/+source/dpkg/tree/lib/dpkg/tarfn.c?h=applied/ubuntu/focal#n554).

To maintain the ability to create archives compatible with deb packages, `format=tarfile.GNU_FORMAT` should be passed to `tarfile.open`.

See related https://github.com/termux/termux-create-package/issues/18

Closed by https://github.com/bazelbuild/rules_pkg/pull/201

**Comment by itdaniher** [comment] 2020-07-13 22:56
Ubuntu 20.04, Bazel version 3.3.1, rules_pkg version 0.2.6.

**Comment by andrewalker** [comment] 2020-07-14 13:09
pkg_tar also have issues when using PAX format: https://github.com/bazelbuild/rules_pkg/pull/204

**Comment by aiuto** [comment] 2020-07-14 14:02
When adding tarballs as input for other tarballs (i.e. `pkg_tar` that depends on another `pkg_tar`), every file with a name that exceeds 98 characters will not land in the new root directory (`package_dir` attribute), but rather on the actual root.

Consider the following example:

    pkg_tar(
        name = "foo",
        package_dir = "/foo",
        strip_prefix = ".",
        srcs = [ ... ],
        deps = [":big-names"],
    )

    pkg_tar(
        name = "big-names",
        strip_prefix = ".",
        srcs = [
            "ninety-eight-characters-seems-to-be-the-maximum-limit-for-merged-tarballs-in-the-rules_pkg-for-bzl",
            "ninety-eight-characters-seems-to-be-the-maximum-limit-for-merged-tarballs-in-the-rules_pkg-for-bzl-",
        ],
    )

The foo tarball will have the following structure:

    .
    ├── foo
    │   └── ninety-eight-characters-seems-to-be-the-maximum-limit-for-merged-tarballs-in-the-rules_pkg-for-bzl
    └── ninety-eight-characters-seems-to-be-the-maximum-limit-for-merged-tarballs-in-the-rules_pkg-for-bzl-

Filenames with 98 characters or less get included in the right directory, but the larger ones go to the root. A deep directory structure behaves the same way:

    .
    ├── foo
    │   └── ninety/eight/characters/seems/to/be/the/maximum/limit/for/merged/tarballs/in/the/rules_pkg/for/bzl
    └── ninety/eight/characters/seems/to/be/the/maximum/limit/for/merged/tarballs/in/the/rules_pkg/for/bzl-

And the size of the package_dir has no influence: "/f", "/foo" or "/foo/bar/baz/quux" behaves exactly the same way.

**This only happens on Python 3.8.** The reason is the default format changed from `tarfile.GNU_FORMAT` to `tarfile.PAX_FORMAT`. It's also possible to reproduce this by changing the format in archive.py to PAX_FORMAT explicitly.

To fix it, I'm explicitly requesting GNU_FORMAT even on 3.8, so that it continues to work as before.

**Closed by aiuto** 2020-07-14 14:02 UTC

**Comment by DhashS** [comment] 2020-07-16 19:06
@aiuto can you reopen this issue? The underlying bug remains unfixed

**Comment by CareF** [comment] 2022-08-27 10:54
Atill have the issue

**Comment by aiuto** [comment] 2022-08-28 04:41
Yes. Have you tried at head just to verify it will work at the next release.

**Comment by CareF** [comment] 2022-08-28 09:20
> Yes. Have you tried at head just to verify it will work at the next release.

I tried patching this PR on top of 0.7.0 and it solves the problem on my hand. Thanks
