### ISSUE TITLE
include_runfiles for pkg_zip?

### ISSUE THREAD

**Issue by njlr** [bazelbuild/rules_pkg#598] opened 2022-07-12 07:27 UTC
`pkg_zip` does not appear to have an `include_runfiles` attribute like `pkg_tar`. 

Is there a work-around for this?

**Comment by aiuto** [comment] 2022-07-26 02:46
Duplicate of #153. When we finish fixing runfiles for tar, we can add it for zip trivially.

**Closed by aiuto** 2022-07-26 02:46 UTC
