### ISSUE TITLE
pkg_files srcs have some file from pkg_files , the sub pkg_files‘s prefix don't take effect

### ISSUE THREAD

**Issue by wondfor** [bazelbuild/rules_pkg#506] opened 2022-01-20 13:30 UTC
the "prefix" of pkg_files cannot be Recursive used when pkg_files used pkg_files

**Comment by nacl** [comment] 2022-01-20 16:06
In the future, please provide more information along with your bug reports, along with minimal reproduction examples that rely as little on external repositories as possible

Anyway, this is by design.  `pkg_files`es cannot be nested with each other, but you can put them them in `pkg_filegroup`s.  You can then then nest `pkg_filegroup`s in other `pkg_filegroup`s.

It might be worth making this emit an error message, but otherwise this probably won't be fixed.

**Closed** 2022-11-22 18:52 UTC
Labels: wontfix
