### ISSUE TITLE
ZIP files contain no directory entries

### ISSUE THREAD

**Issue by guw** [bazelbuild/rules_pkg#638] opened 2022-11-23 08:47 UTC
Zip files produced by `rules_pkg` do not contain directory entries. For example, they look like this:
```
META-INF/MANIFEST.MF
xds/one.xsd
xds/two.xst
```

Although technically not required by the spec, a convention is to add directory entries to zip files (0 bytes, file name ending with `/`). A lot of tools seem to follow/implement this convention. 

Expected:
```
META-INF/
META-INF/MANIFEST.MF
xds/
xds/one.xsd
xds/two.xst
```

Missing directory entries may cause issues with the Java ecosystem, which seems to heavily rely on the directory entries. For example, see this Spring Framework issue:
https://github.com/spring-projects/spring-framework/issues/28230#issuecomment-1324702762

**Comment by aiuto** [comment] 2022-11-23 19:47
Duplicate of #622.

**Closed** 2022-11-24 03:07 UTC
