### ISSUE TITLE
Add support for workspace statuses in pkg_*

### ISSUE THREAD

**Issue by radix-aw** [bazelbuild/rules_pkg#180] opened 2020-05-16 01:11 UTC
### Description of the problem / feature request:

I would like to use variables defined via my `--workspace_status_command` in pkg_* rules.

### Feature requests: what underlying problem are you trying to solve with this feature?

I would like the version of my RPM to contain the branch I am working on (provided by the workspace status command).

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Declare a `pkg_rpm` rule with `version = "{FOO}"`.

### What operating system are you running Bazel on?

Ubuntu Bionic

### What's the output of `bazel info release`?

release 3.2.0rc1

**Comment by aiuto** [comment] 2020-05-19 16:05
I'm not inclined to do this by default.  That would mean every rule would now have to take a dependency on stable-status.txt.  What I could see is a shared attribute env_vars:string_list.
If you set that on any rule you get the dependency on stable_status and enable the lookup, but only for those variable listed. That nicely documents that the rule depends on something outside the BUILD file (perhaps a default can be specified there). I could also see this variable expansion extend into the template and spec files.

It needs a better design before implementing.

**Comment by aiuto** [comment] 2020-05-19 16:40
Duplicate of #53

**Closed by aiuto** 2020-05-19 16:40 UTC
Labels: P3, enhancement, help wanted
