### ISSUE TITLE
pkg_tar can not unzip

### ISSUE THREAD

**Issue by Beichen-Wang** [bazelbuild/rules_pkg#500] opened 2022-01-04 09:12 UTC
the code is :
pkg_tar(
    name = "cudnn8.2.1_runtime_dynamic_lib",
    package_dir = "/home/wangbeichen/tmp/test_cudnn_dynamic_lib",
    srcs = [
        "@cudnn_11_1_x86_64_v8_0_4_archive//:cudnn_shared",
        ],
    mode = "0755",
)
I build sucessfully, but I can't unzip the tar. please help me!!!!

**Comment by nacl** [comment] 2022-01-04 12:59
I'm afraid we can't help without additional information.  A minimal reproducing example would be very helpful.  What did you run to try to extract the tarfile?

One thing to note is that `pkg_tar` produces a tar file that must be extracted using a command like `tar -xf`.  `unzip` extracts only zip files, which are produced by `pkg_zip`.

**Comment by nacl** [comment] 2022-01-24 16:03
Closing since we haven't received a response.  Please feel free to provide more details and reopen.

**Closed by nacl** 2022-01-24 16:03 UTC
Labels: need more information
