### ISSUE TITLE
RFC: building rpm with https://github.com/google/rpmpack

### ISSUE THREAD

**Issue by sluongng** [bazelbuild/rules_pkg#295] opened 2021-02-21 18:29 UTC
Instead of shelling out and depending on `rpmbuild` binary from python script https://github.com/bazelbuild/rules_pkg/blob/main/pkg/make_rpm.py,

We can instead relying on the API available in https://github.com/google/rpmpack and construct the runner executable programmatically. More over, not having dependencies on `rpmbuild`, and instead a golang library, will increase the hermeticity of the rules overall.

This is what currently being used in https://github.com/ericnorris/rules_nfpm which depends on https://github.com/goreleaser/nfpm/ which uses https://github.com/google/rpmpack API.

**Comment by aiuto** [comment] 2021-02-23 02:40
This is essentially a duplicate of #29.  I am moving this there so we have move the discussion there.

**Closed by aiuto** 2021-02-23 02:40 UTC
